// Do not edit. This file is machine generated by the Resource DLL Wizard.

library AdventureCreatorIDE;

{ITE} {DFMFileType} {AdventureCreatorIDEMain.dfm}
{ITE} {DFMFileType} {ChoiceCommandsForm.dfm}
{ITE} {DFMFileType} {MetaData.dfm}
{ITE} {DFMFileType} {VarEditor.dfm}
{ITE} {RCFileType} {C\CodeProjects\AdventureCreator\AdventureCreatorIDE_DRC.rc}

{$R 'AdventureCreatorIDEMain.dfm' 'Form1:TForm'}
{$R 'ChoiceCommandsForm.dfm' 'Form4:TForm'}
{$R 'MetaData.dfm' 'Form2:TForm'}
{$R 'VarEditor.dfm' 'Form3:TForm'}
{$R 'C\CodeProjects\AdventureCreator\AdventureCreatorIDE_DRC.res' 'C\CodeProjects\AdventureCreator\AdventureCreatorIDE_DRC.rc'}

{$E FIN}

begin
end.
